version: '3.1'

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_USERNAME: my_user
      MONGODB_PASSWORD: user
      MONGODB_DATABASE: django_mongodb
      MONGODB_EXTRA_FLAGS: --wiredTigerCacheSizeGB=2
  web:
    image: app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      MONGODB_DATABASE: django_mongodb
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: mongoadmin
      MONGODB_HOSTNAME: mongodb
    volumes:
      - .:/gettingstarted
    ports:
      - 8000:8000
    links:
        - mongodb

