version: '3.1'

volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig:


services:
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      MONGODB_DATABASE: django_mongodb
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: mongoadmin
      MONGODB_HOSTNAME: mongodb
    volumes:
      - .:/gettingstarted
    ports:
      - 8000:8000
    links:
      - mongodb
    depends_on:
      - migration
    networks:
      - backend

  mongodb:
    image: mongo:4.2.3-bionic
    container_name: my-mongodb-container
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=django_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./data-db:/data/db
    networks:
      - backend

  migration:
    build: .
    image: app
    command: python manage.py migrate
    volumes:
      - .:/gettingstarted
    links:
      - mongodb
    depends_on:
      - make_migrations

  make_migrations:
    build: .
    image: app
    command: python manage.py makemigrations
    volumes:
      - .:/gettingstarted
    links:
      - mongodb
    depends_on:
      - mongodb


networks:
  backend:
    driver: bridge

