version: '3.1'

volumes:
  init-db:
  data-db:

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./data-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: django_mongodb
    ports:
      - 27017:27017
    networks:
      - backend

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
    links:
      - mongo
    networks:
      - backend

  web:
    image: app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      MONGODB_DATABASE: django_mongodb
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: mongoadmin
      MONGODB_HOSTNAME: mongodb
    volumes:
      - .:/gettingstarted
    ports:
      - 8000:8000
    links:
      - mongo
    depends_on:
      - mongo
      - migration
    networks:
      - frontend
      - backend

  migration:
    build: .
    image: app
    command: python manage.py migrate
    volumes:
      - .:/gettingstarted
    links:
      - mongo
    depends_on:
      - make_migrations

  make_migrations:
    build: .
    image: app
    command: python manage.py makemigrations
    volumes:
      - .:/gettingstarted
    links:
      - mongo
    depends_on:
      - mongo

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

