version: '3.1'

volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig:


services:
  web:
    image: python
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      MONGODB_DATABASE: django_mongodb
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: mongoadmin
      MONGODB_HOSTNAME: mongodb
    volumes:
      - .:/gettingstarted
    ports:
      - 8000:8000
    links:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:4.2.3-bionic
    container_name: my-mongodb-container
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=django_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - backend

networks:
  backend:
    driver: bridge

